// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginUser struct {
	Name     string `json:"Name"`
	Password string `json:"Password"`
}

type NewProfile struct {
	Name                  string `json:"Name"`
	WorkblockDuration     int    `json:"WorkblockDuration"`
	RestblockDuration     int    `json:"RestblockDuration"`
	LongRestblockDuration int    `json:"LongRestblockDuration"`
	NWorkblocks           int    `json:"NWorkblocks"`
}

type NewUser struct {
	Name     string `json:"Name"`
	Password string `json:"Password"`
}

type Profile struct {
	ID                    int    `json:"ID"`
	Name                  string `json:"Name"`
	WorkblockDuration     int    `json:"WorkblockDuration"`
	RestblockDuration     int    `json:"RestblockDuration"`
	LongRestblockDuration int    `json:"LongRestblockDuration"`
	NWorkblocks           int    `json:"NWorkblocks"`
}

type User struct {
	ID       int     `json:"ID"`
	Name     string  `json:"Name"`
	Password *string `json:"Password"`
}
